### ISSUE TITLE
Low audio volume in AC3 5.1 with Ubuntu+SyncLounge Player

### ISSUE THREAD

**Issue by ipsingh06** [samcm/synclounge#103]
OS: Ubuntu 16.04
Browser: Chrome or Firefox (happens on both)
Player: SyncLounge Player

When playing a video with AC3 5.1 audio, the volume is low and the balance between dialog and music is off. This doesn't happen under Plex Web. It happens on both Firefox and Chrome with SyncLounge Player. I suspect it has something to do with the 5.1 channels not being properly converted to stereo.

**Comment by Celant** [comment]
Happening on both web and desktop Plex Media Player apps for me. 5.1 audio is being incorrectly downmixed and it's only playing side audio?
