### ISSUE TITLE
Unable to connect - Try disabling adblocker

### ISSUE THREAD

**Issue by Choze96** [samcm/synclounge#104]
Hi,

a friend and I experience the same problem at random moments.
About 50% of the time, we are able to connect without any problem to another friend's synclounge.
The other 50%, we are blocked by a message saying "Unable to connect. Try Disabling your adblocker." 
![synclounge](https://user-images.githubusercontent.com/49463475/55846630-60062600-5b14-11e9-881c-355cddedc92f.PNG)

I use Google Chrome and don't have a proxy.

What we have tried so far : 

- Whitelisting Synclounge on our adblocklers.
- Disabling our adblockers
- Trying to connect on other browers (i tried firefox, edge and i even installed opera to try it)
- Trying to connect with the owner's account
- Trying to create a new room myself (even my room is blocked for me)

**Comment by Choze96** [comment]
After multiple tries it looks like the owner had a VPN. 

Since he disabled it I don't have the problem anymore...

**Comment by samcm** [comment]
Haha that'd explain that! 👍
