### ISSUE TITLE
Switching quality or enabling subtitles restarts playback

### ISSUE THREAD

**Issue by evaera** [samcm/synclounge#109]
When in the middle of watching something, if I switch the quality or change the subtitle track, the video restarts from the beginning. It would be a better experience if the player remembered my position when I change settings.

**Comment by MarioRicalde** [comment]
I second this. Not only this is a UX issue but also a performance one. Sometimes when you switch subtitles and the video restarts the sync breaks and it won't fix until the tab is refreshed.

**Comment by dsringari** [comment]
Thirding this.

**Comment by evaera** [comment]
...

**Comment by ttshivers** [comment]
This issue should be fixed in the current release of synclounge. Are you still experiencing this issue @evaera ?

**Comment by evaera** [comment]
Fixed!
