### ISSUE TITLE
Allowing Leader Delegation

### ISSUE THREAD

**Issue by aileron565** [samcm/synclounge#115]
The idea is to be able to promote another user in the room to be the leader. This would be nice if you want someone else to pick the next media and such. Currently the only work around is to have the current leader leave and rejoin and if needed rinse and repeat until the correct person is selected.

One way this could be implemented is to have a star outline next to each user (similar to the current leader indicator) which the leader can click to promote that person to the leader and in turn demote themselves.

**Comment by gcordalis** [comment]
This is already implemented, however not communicated well in the UI. Double clicking the avatar of someone else in the room will give them the leader role.
