### ISSUE TITLE
Disable SLPlayer Force Transcode by default

### ISSUE THREAD

**Issue by Too5shot** [samcm/synclounge#117]
Is there a way to disable SLPlayer Force Transcode by default ?

**Comment by gcordalis** [comment]
>Is there a way to disable SLPlayer Force Transcode by default ?

@Too5shot 

You can turn off force transcode under the SyncLounge settings in the menu on the top left.

**Comment by Too5shot** [comment]
Yeah i figured that out, but is there a way to have that be toggled off by default when someone connects to my server ?

**Comment by gcordalis** [comment]
No there isn't. It's not a preset setting because direct play isn't completely stable and the user experience is much better when transcoding is forced.

**Comment by korvyr** [comment]
Can this be changed to a default setting somewhere for those of us running out own SyncLounge server? I run movie nights and we have dozens of people connecting. Forcing transcode for everyone **destroys** my server's CPU.

**Comment by Too5shot** [comment]
Hi @korvyr 

I edited constants.js and settings.js under "synclounge/src/utils" and got i working with transcoding disabled by default.

**My constants.js**

import { generateGuid } from './helpers';

export const defaultSettings = {
  CLIENTPOLLINTERVAL: 1000,
  AUTOPLAY: true,
  AUTOJOIN: true,
  HIDEUSERNAME: false,
  DARKMODE: false,
  SYNCMODE: 'cleanseek',
  SYNCFLEXABILITY: 3000,
  CUSTOMSERVER: '',
  SLPLAYERFORCETRANSCODE: false,
  CLIENTIDENTIFIER: `${generateGuid()}-${generateGuid()}`,
  blockedServers: [],
  LASTSERVER: '',
};

export default {
  defaultSettings,
};

**And my settings.js**

import { defaultSettings } from './constants';
import { get } from './storage';

const keys = [
  'AUTOPLAY',
  'CLIENTPOLLINTERVAL',
  'SYNCMODE',
  'SYNCFLEXABILITY',
  'CUSTOMSERVER',
  'BLOCKEDSERVERS',
  'HOMEINIT',
  'PTPLAYERQUALITY',
  'PTPLAYERVOLUME',
  'SLPLAYERFORCETRANSCODE',
  'HIDEUSERNAME',
  'ALTUSERNAME',
  'CLIENTIDENTIFIER',
  'LASTSERVER',
];

export const getAll = () => {
  const settings = {};
  keys.forEach((key) => {
    settings[key] = get(key);
    return true;
  });
  // Accept the default setting if the persisted value is null or undefined
  Object.keys(settings).forEach((key) => {
    if (settings[key] === undefined || settings[key] === null) {
      settings[key] = defaultSettings[key];
    }
  });
  return settings;
};

export default {
  getAll,
};
