### ISSUE TITLE
Reverse proxy to subfolder

### ISSUE THREAD

**Issue by burkasaurusrex** [samcm/synclounge#119]
So I'm able to reverse proxy synclounge to `synclounge.domain.com` but I haven't been able to get any configuration to work for `my.domain.com/synclounge`. Is this not supported or am I missing some key config?

**Comment by topper59** [comment]
Yeah I also have this issue, I think it's because the SL webapp only supports the root domain/subdomain, so domain.com or sl.domain.com would work but not anything else. I've tried messing with webroot and serverroot settings but looks like nothing works. This creates an issue for me because domain.com leads to plex and domain.com/sync I want to be synclounge, but instead it just redirects to plex because it's forcing the root domain.

**Comment by topper59** [comment]
Ah figured it out, set webroot to /synclounge in settings.json and run npm install and npm run build again.

**Comment by burkasaurusrex** [comment]
So, for posterity, you can set the client path with 'webroot' in the config or 'WEB_ROOT' as an env variable. Same with 'serverroot' or 'SERVER_ROOT'.

However, after a while of trying to do a reverse proxy, I've determined that you can't have the server root be in the same path as the webroot (e.g. example.com/synclounge and example.com/synclounge/server). I was able to route around all but one of the socket.io requests that continually returned a 'invalid namespace' error.

I will add that if they are different paths (e.g. example.com/synclounge and example.com/synclounge-server) you can run the following location blocks in nginx without a problem:

```
location = /config {
	return 301 http://www.example.com/synclounge/config;
}

location /synclounge/socket.io {
	rewrite /synclounge/socket.io/(.*) /synclounge-server/socket.io/$1 break;
	proxy_pass http://<ip-address>:8089/synclounge-server/socket.io;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	
	proxy_redirect off;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Accept-Encoding identity;
}

location /synclounge-server/ {
	proxy_pass http://<ip-address>/synclounge-server/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";

	proxy_redirect off;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Accept-Encoding identity;	
}

location /synclounge/ {
	proxy_pass http://<ip-address>:8088/synclounge/;
	proxy_http_version 1.1;

	proxy_redirect off;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Accept-Encoding identity;
}
```

Would appreciate any suggestions if someone has an idea on how to fix the invalid namespace error

**Comment by topper59** [comment]
Thanks for this! Can't help ya with the namespace error, but I just put my server on a different path and it works perfectly.
