### ISSUE TITLE
Unable to connect to Apple TV

### ISSUE THREAD

**Issue by macstainless** [samcm/synclounge#120]
When trying to use SyncLounge with my Apple TV, I'm given the following error almost instantly after pressing the Connect button on the web: "Unable to connect to client".

Operating System: MacOS Mojave
Web Browser name and version: Safari 12.1.2
Plex Media Server details
Version 1.16.3.1402 
Operating System MacOS Mojave 
Location (Local/Remote) Local
Plex Client details
Name Apple TV
Version: 1.40.1
Network connection (Wired/Wifi) Wired
Platform: Apple TV

**Comment by mauran** [comment]
Just bumping to tell that this still occurs. We should probably update the README.md

**Comment by joshuata** [comment]
It looks like a problem with CORS - I wonder if the Apple TV isn't using the https remote control protocol

**Comment by paviro** [comment]
I am having the same problem unfortunately.
