### ISSUE TITLE
HE-AAC Stereo Audio Track not playing

### ISSUE THREAD

**Issue by Daynar100** [samcm/synclounge#128]
Hello, so my friend and I discovered that synclounge fails to play audio types listed as HE-AAC in plex. They appear as ACC Unknown in synclounge. We are able to play the video with sound fine in plex. They just fail to play with audio in synclounge.

**Comment by samcm** [comment]
This is probably an issue with the video player we're using but maybe its something weird with how we handle the tracks/transcoding.
