### ISSUE TITLE
Custom Server

### ISSUE THREAD

**Issue by Kagelol** [samcm/synclounge#129]
Hi there, 

Today the Synclounge EU server (and US) went down, so i figured i might as well start running my custom server. I use Synlounge a lot and i love it!  (Goodjob!!) 
However i cannot seem to working properly. I loaded the dockerfile oin my Synology and i portforwarded External ports to my Synology ports.
When i go to the webpage with port 8088 i actually get to see Synclounge webpage
When i go to the page on port 8089 I get to see "You've connected to the SLServer, you're probably looking for the webapp."
(this is from external network on a hostname i got pointing to my external ip)

So i opened the webapp, and filled in my custom server hostname, but it keeps saying it cannot connect. Which i do not understand since I think I forwarded them properly, especially since i get to see the page when I go to it Directly.

What could i be doing wrong?

**Comment by samcm** [comment]
Heya, this could potentially just be a missing `/slserver` at the end of your cusom server address input :)

EG. `http://localhost:8089/slserver`. 

Let me know how you go 👍

**Comment by Kagelol** [comment]
Ah yes.. You're right.
It was that.  I had tried it, but with capitalised SLServer.
The small for it did get.
Thank you, and sorry for the stupid question 🤦‍♂
