### ISSUE TITLE
Web UI Not Loading

### ISSUE THREAD

**Issue by eeverett91** [samcm/synclounge#141]
Just upgraded to the newest version both via in-place upgrade and a fresh install but suddenly my UI no longer loads. The index.html / page source does load but all JS and CSS artifacts do not. Logs show these messages.

Mar 15 18:41:10 sync-ct systemd[1]: Started Synclounge App.
Mar 15 18:41:11 sync-ct node[42690]: Settings { webroot: '/',
Mar 15 18:41:11 sync-ct node[42690]:   webapp_port: '8088',
Mar 15 18:41:11 sync-ct node[42690]:   accessUrl: 'http://sync.WEBSITE.com',
Mar 15 18:41:11 sync-ct node[42690]:   serverroot: '',
Mar 15 18:41:11 sync-ct node[42690]:   server_port: '8089',
Mar 15 18:41:11 sync-ct node[42690]:   autoJoin: true,
Mar 15 18:41:11 sync-ct node[42690]:   autoJoinServer: 'https://sync.WEBSITE.com/slserver',
Mar 15 18:41:11 sync-ct node[42690]:   autoJoinRoom: 'ROOM',
Mar 15 18:41:11 sync-ct node[42690]:   autoJoinPassword: 'PWD' }
Mar 15 18:41:11 sync-ct node[42690]: Basesettings { waterline:
Mar 15 18:41:11 sync-ct node[42690]:    { models: { invite: [Object] },
Mar 15 18:41:11 sync-ct node[42690]:      defaultModelSettings:
Mar 15 18:41:11 sync-ct node[42690]:       { primaryKey: 'id', datastore: 'defaults', attributes: [Object] } },
Mar 15 18:41:11 sync-ct node[42690]:   database: { datastores: { defaults: [Object] } } }
Mar 15 18:41:11 sync-ct node[42690]: Sun, 15 Mar 2020 18:41:11 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at webapp.js:68:12
Mar 15 18:41:11 sync-ct node[42690]: Sun, 15 Mar 2020 18:41:11 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29
Mar 15 18:41:11 sync-ct node[42690]: SyncLounge WebApp successfully started on port 8088
Mar 15 18:41:11 sync-ct node[42690]: Running with base URL: /
Mar 15 18:41:11 sync-ct node[42690]: Access URL is http://sync.WEBSITE.com
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /js/app.6837483ba9b1e14da703.js
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /css/app.a5511c6bc652b43679174f0c22ff192b.css
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /js/vendor.98550486d41f5ec5fe20.js
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /js/manifest.c33ac5aee1bb047d37cd.js
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /favicon.ico
Mar 15 18:41:27 sync-ct node[42690]: Catch all: /favicon.ico

When trying to access one of the files directly (e.g. the CSS file), browser shows ERR_INVALID_REDIRECT

Any ideas?

**Comment by MagicalCodeMonkey** [comment]
This should be fixed in PR https://github.com/samcm/synclounge/pull/139. For now, don't set webroot to `/`

**Comment by Cimplex** [comment]
You can't leave it empty though, the SettingsHelper.js changes it to '/':
```js
    // Add leading slash, if not provided
    if (setting.local == 'webroot' && !output[setting.local].startsWith("/")) {
      // Make sure it starts with one leading slash
      output[setting.local] = `/${output[setting.local]}`;
    }
```
I had to add this to make it work:
```js
    output.webroot = '';
    return output;
}
````

**Comment by maxpereira** [comment]
You can also remove the slash from webapp.js to make it work:
`  root.use(`${settings.webroot}`/, express.static(path.join(__dirname, 'dist')));`
becomes
`  root.use(`${settings.webroot}`, express.static(path.join(__dirname, 'dist')));`

**Comment by MagicalCodeMonkey** [comment]
@Cimplex Ah! Yeah, that's a bug that will be fixed when https://github.com/samcm/synclounge/pull/139 is merged in
