### ISSUE TITLE
Unable to connect to the server from web app

### ISSUE THREAD

**Issue by SethGower** [samcm/synclounge#145]
Hello, I am trying to set this up on my network with docker and nginx. I am using the latest version of the docker image. I set it up in a docker-compose file (below). I am able to access the web app, and that seems to work, but the web app is unable to reach the server. I am not sure what is happening. If I connect to the server from the browser (`synclounge.example.com/slserver`) it shows the message saying I meant to connect to the web app. I am using the recommended nginx setup (with SSL added using `certbot`). What do I need to put into the server connection field on the web app to connect to the server? I have tried
( have replaced the actual domain with a dummy one)
- `http://synclounge.example.com/slserver`
- `http://synclounge.example.com:8089/slserver`
- `http://synclounge.example.com:8089`

None of these have worked, please help. 
```docker-compose
version: "2"
services:
        synclounge:
                image: starbix/synclounge
                network_mode: host
                container_name: SyncLounge
                restart: unless-stopped

```

**Comment by weinberz** [comment]
This is exactly the issue I'm seeing in #143 . Try opening up the JavaScript console in your browser and seeing what message gets sent when you try to connect?

**Comment by maxpereira** [comment]
This issue is popping up because the server is being served over plain HTTP and the webapp is being served over HTTPS. You need to match protocols. I am running into this issue right now and am attempting to make this work.

**Comment by weinberz** [comment]
Both server and webapp are running via http for me.

**Comment by samcm** [comment]
Could you please post your Nginx conf?

**Comment by SethGower** [comment]
I got mine working. It was the difference between HTTPS and HTTP.
