### ISSUE TITLE
Chat on mobile

### ISSUE THREAD

**Issue by eskemojoe007** [samcm/synclounge#146]
To me one of the best features of SyncLounge is the ability to chat with each other while watching.  I love the full browser feature for this.  I see that #42 is about chatting when in full screen which is awesome.

The use case of this enhancement would be slightly different.  I want to be able to chat with my friends and family on my mobile device while it plays on an external player like my Roku or AppleTV.  

Workflow would be: Open room on my mobile browser, select my TV player, select content, select chat, then have the chat on my phone while it plays on my TV.  

This seems to work if I initiate everything from my full PC, play it on my TV, then sit at my PC and chat.  The chat features disappear on devices smaller than about 1263px wide it seems.

**Comment by samcm** [comment]
Hey, thanks for the issue. This one shouldn't be too bad to fix. I'm actually surprised it doesn't work at the moment (it certainly used to). I'll find some time 👍

**Comment by uberjay** [comment]
Another way to get at this sort of feature would be to add the ability to join without video playback -- basically, a chat-only client on your phone.
