### ISSUE TITLE
Not transfering host in room user from user because its role is guest

### ISSUE THREAD

**Issue by Logh0nox** [samcm/synclounge#148]
When I create my own server in linux I get this message every time I join the server.
Also I got message in the chat that I leaved the room

**Comment by samcm** [comment]
Are you the only user in the server?

**Comment by Logh0nox** [comment]
when the error happened, no, it needs to be 2 users to this happen

**Comment by MagicalCodeMonkey** [comment]
@Logh0nox Is this still happening after you update to the latest version?

**Comment by Logh0nox** [comment]
yes I still have the error, after a second use join the channel I get:
Transfering host in room loghonox from Loghonox to user@gmail.com
Not transfering the host in the room loghonox because the room was already destroyed
