### ISSUE TITLE
Warn of pop up blocking for Plex Sign In

### ISSUE THREAD

**Issue by joecot** [samcm/synclounge#155]
The Plex Sign In button opens a popup to plex.tv sign-in. As noted in #154 if the popup is blocked by your browser, the button does nothing, there's a vague error in the console, and there's no indication of what went wrong. Some browsers might give a better idea of the error, but my Firefox just silently blocked the popup until I turned it off for the site.

It'd be useful if SyncLounge caught the error of not getting a new window, and included some warning on the page about disabling the pop up blocking.

**Comment by MagicalCodeMonkey** [comment]
Done! This can be closed when merged 😃

**Comment by samcm** [comment]
Thanks all!
