### ISSUE TITLE
Custom Server Issues

### ISSUE THREAD

**Issue by MBRO95** [samcm/synclounge#156]
The CUSTOM_SERVER env variable is being ignored.

Additionally, if i set SERVERS with only the Custom Server defined, this causes the server screen in the web app to freak out and make unlimited test connection boxes down the screen.

I am using Docker Desktop on Windows w/ docker-compose.
I have tried :latest and :dev and no success. :dev seems to ignore CUSTOM_SERVER & SERVERS completely.

Here is my docker-compose.yml:

`version: '3.3'
services:
   SyncLounge:
     image: starbix/synclounge:latest
     ports:
       - "8888:8088"
       - "8899:8089"
     expose:
       - 8888
       - 8899
     restart: always
     environment:
       DOMAIN: synclounge.mrmsquared.com
       WEB_ACCESSURL: http://synclounge.mrmsquared.com
       AUTOJOIN_ENABLED: "false"
       AUTHENTICATION:
        '{
          "mechanism": "plex",
          "type": "server",
          "authorized": "e9f80ec81e5e3238d73abf1ef8d1a3caeb67b190"
        }'
       CUSTOM_SERVER:
        '[{
          "name": "MMNET | SyncLounge",
          "location": "Phoenixville, PA, USA",
          "url": "http://server.synclounge.mrmsquared.com/slserver",
          "logo": "http://synclounge.mrmsquared.com/flags/usa.png"
       }]'`

**Comment by MagicalCodeMonkey** [comment]
CUSTOM_SERVER env variable should be fixed when https://github.com/samcm/synclounge/pull/149 is merged.

In your YML, you have CUSTOM_SERVER as an array but should just be the object `{}` (which doesn't matter since that is borked right now). For SERVERS it must be an array. Try changing `CUSTOM_SERVER` to `SERVERS` and see if it works then.

**Comment by MBRO95** [comment]
Hey thanks for the quick reply. Unfortunately, no dice on either of those options.

For the CUSTOM_SERVER env, I get an infinite loop of creating “Connect” buttons with a “Testing connection...” comment.

For the SERVERS env, I get the normal server list - custom server is just the default one and it doesn’t even substitute the URL there.

Best Regards,

Matt May
