### ISSUE TITLE
Authorization by email/username does not appear to work

### ISSUE THREAD

**Issue by myhandsareblue** [samcm/synclounge#157]
Previously discussed on Discord with MagicalCodeMonkey, opening an issue per request as a reminder.

When I've configured usernames and/or email addresses only in my authentication config, I still get an unauthorized error even when I've logged in with a Plex account matching the username/password.

**Comment by MagicalCodeMonkey** [comment]
Yuppp... It's because I was dumb and forgot something. 
Once https://github.com/samcm/synclounge/pull/149 is merged, it should work!
