### ISSUE TITLE
Authentication: Machine ID needs to be ProcessedMachineIdentifier, not MachineIdentifier

### ISSUE THREAD

**Issue by myhandsareblue** [samcm/synclounge#158]
Discussed on discord with MagicalCodeMonkey, opening an issue per request as a reminder.

Currently, the README documentation suggests using a Plex Machine ID for server authentication.  I used this guide from Plex to retrieve my Plex Machine ID via regedit: https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/

When I take the stored value under MachineIdentifier, server authorization does not appear to work.  I tried logging in with several users that had access to the server.  However, when I used the value from ProcessedMachineIdentifier, server authorization works just as expected (authorizes users that have access to the server, and users not added to the server received an unauthorized error).

I would recommend posting the linked Plex article to retrieve the Machine ID in the README, as well as updating to clarify the value needed is ProcessedMachineIdentifier to avoid confusion.  Thank you!

**Comment by MagicalCodeMonkey** [comment]
Thanks!

Does the ProcessedMachineIdentifier match `machineIdentifier` for your server when you use one of these?
https://plex.tv/pms/servers.xml?includeHttps=1&X-Plex-Token=YourTokenGoesHere
http://[PMS_IP_Address]:32400/?X-Plex-Token=YourTokenGoesHere

To get your token, follow these instructions: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by camisatx** [comment]
Thanks @myhandsareblue! I had the same issue. Using `ProcessedMachineIdentifier` solved the issue of server authorized users not being able to log into synclounge.

As per @MagicalCodeMonkey's question, my Plex server's `ProcessedMachineIdentifier` and `machineIdentifier` were different.

For anyone else finding this, you can access the `ProcessedMachineIdentifier` within `config/Library/Application Support/Plex Media Server/Preferences.xml`.

**Comment by MagicalCodeMonkey** [comment]
I see now. The `ProcessedMachineIdentifier` in the XML is the same as the `machineIdentifier` that is listed in the `<Server` object for you server at `https://plex.tv/pms/servers.xml?includeHttps=1&X-Plex-Token=YourTokenGoesHere` which is what I was asking. 

It's a bit annoying, and confusing, that they use the same terminology in different ways... I'll update the documentation to reflect this and be a bit clearer on how to get the value. Thanks!
