### ISSUE TITLE
server.js does not honor settings.json file for port

### ISSUE THREAD

**Issue by joecot** [samcm/synclounge#160]
server.js is not getting the port from the settings.json file, and is only getting it from environment variables.

This appears to be a result of this commit:
https://github.com/samcm/synclounge/commit/de0b69a3bdb2d70c180467ad9895d038ea7416ac#diff-5a75ae4cace615ff004091240d3b1c97

```
-    process.env[setting.env] = output[setting.local];
+    process.env[setting.local] = output[setting.local];
```
To set the environment variable names correctly. The issue is that server.js is using:
```
const PORT = process.env.server_port || 8089;
```
Checking server_port instead of SERVER_PORT. To fix this change to:
```
const PORT = process.env.SERVER_PORT || 8089;
```

**Comment by MagicalCodeMonkey** [comment]
Made a PR to fix it. Thanks for catching this and reporting it quickly!

**Comment by samcm** [comment]
Thanks all! @joecot I'll leave the closing to you if the above PR fixes the issue 👌

**Comment by joecot** [comment]
Tried and the port works correctly, thanks folks!
