### ISSUE TITLE
SyncLounge Docker guide

### ISSUE THREAD

**Issue by jacobmix** [samcm/synclounge#162]
Here's a guide on how to run SyncLounge with Docker on Synology: 
https://gist.github.com/jacobmix/32003649e06d5588dba35e5edafa5d7b

**Comment by samcm** [comment]
Thanks mate, this is awesome ❤️

**Comment by samcm** [comment]
Will add to the readme tomorrow 👍

**Comment by 0xdevalias** [comment]
When you update the docker guide, would you be able to also include some more detailed instructions on the best way to configure `AUTHENTICATION`, etc via ENV vars please?

Currently i'm attempting to set it as follows.. but not sure that is right:

```
-e 'AUTHENTICATION'='{ "mechanism": "plex", "type": ["server", "user"], "authorized": ["foo@example.com", "machine-id-foo-bar", "etc"] }'
```

**Comment by xxbiohazrdxx** [comment]
So should I use the built in Synology reverse proxy? Or the container w/ nginx? 

Ideally I would be able to use the Synology reverse proxy so that it easily integrates w/ Let's Encrypt.

Do both the server and web client need to be internet accessible, or just the client?

**Comment by racela** [comment]
Hi guys, for those of us that just wanna use our public IP (I plan to share my server with a couple of close friends) but don't have a static IP, would we have to delete the container and run the image with the appropriate IP every time it changes? Sorry if this has been asked before. Thanks!
