### ISSUE TITLE
Guide for Self-Hosting SyncLounge without Docker

### ISSUE THREAD

**Issue by joecot** [samcm/synclounge#163]
I created a guide for Self-Hosting SyncLounge without Docker, just using nodejs and pm2
https://gist.github.com/joecot/2b6fb52f72ca8022cacc4543fe1bed1b

If that seems sufficient as a guide, please consider linking it from the readme

**Comment by samcm** [comment]
You're an absolute legend, I'll 100% add it to the readme. Thanks!

**Comment by Cookie-Monster-Coder** [comment]
@joecot Thank you for this, it's so much better than the current one!

One question, I'm wondering if it's possible to disable Plex auth. I tried setting `"mechanism":"none",` but still asking for auth

**Comment by joecot** [comment]
@Cookie-Monster-Coder I've updated the guide to describe that, but the gist is that while you could leave authentication as none, the user will _still_ need to sign in with their plex account, because all SyncLounge is doing is streaming the video them them via their plex login, and syncing up the times. The reason for defaulting to authorizing by machine is that in 95% of cases, you're going to be streaming the video to them from your plex server, so authenticating at the beginning that you've shared the plex server with them is easier than waiting for them to join a room and it not working.

**Comment by samcm** [comment]
Thanks again mate. @MagicalCodeMonkey what do you think of pulling this in to its own section under self-hosted in docs?

**Comment by MagicalCodeMonkey** [comment]
Done! 😄 http://docs.synclounge.tv/self-hosted/linux/

**Comment by joecot** [comment]
@MagicalCodeMonkey  I've updated the server url in the settings.json in the gist, please update on the site when you have a chance

**Comment by MagicalCodeMonkey** [comment]
I'll take a look when I can! You can also make edits yourself at any point if you pull up the page and click the Pencil icon to edit it. It should automatically create a branch and PR for your edits when you commit the changes.

**Comment by MagicalCodeMonkey** [comment]
Updates incoming!
