### ISSUE TITLE
Quota exceeded when chunks are too large on Firefox

### ISSUE THREAD

**Issue by pet0ruk** [samcm/synclounge#165]
Thanks for the great project!

Seems like this issue happens - https://github.com/videojs/http-streaming/issues/258 when streaming content and the HLS chunks are >20MB, but it's fixed upstream in https://github.com/videojs/http-streaming/issues/192

But I noticed you are `videojs/videojs-contrib-hls` which has been deprecated in favour of `videojs/http-streaming` - are there any plans to switch over to that?

**Comment by samcm** [comment]
Thanks! That issue has a nice little snippet that might help. Both myself and @bool- have tried updating SL to use vjs7 and the issue still persisted, this might fix it though 😄

**Comment by ttshivers** [comment]
This issue will be fixed in a future release once #216 gets integrated.
