### ISSUE TITLE
[Feature Request]Anyway to get auth working with Organizr SSO

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [samcm/synclounge#168]
Would be awesome if this could work with Organizr SSO (https://github.com/causefx/Organizr), as from a user standpoint, the user only needs to login once. Organizr already auths with Plex, so passing a success cookie might be an option?

**Comment by MagicalCodeMonkey** [comment]
PR https://github.com/samcm/synclounge/pull/169 made to update this on the SyncLounge side
