### ISSUE TITLE
Synclounge doesn't ever fully pause

### ISSUE THREAD

**Issue by cmeyertons** [samcm/synclounge#179]
On my initial testing of my custom server setup, synclounge gets stuck in a "pause loop"

![YWIDx5uIjF](https://user-images.githubusercontent.com/19917677/78785029-007f6800-796c-11ea-92ac-0fa449894d13.gif)

- running two Chrome tabs with the sam
e Plex account (each pointed to a different client)
- host device is a Roku Streaming Stick+
- guest device is a Roku Streaming Stick+
- all devices (Synclounge + 2 Rokus + Plex) are all on the same network
- i am navigate to Synclounge through a custom domain I own (e.g. www.mydomain.com)
- `starbix/synclounge:latest`

**Comment by gcordalis** [comment]
It's an issue with the roku player unfortunately - at this stage not something we have workaround for.
