### ISSUE TITLE
NVIDIA Shield Plex Client no longer works properly

### ISSUE THREAD

**Issue by rettw78** [samcm/synclounge#181]
Hi - 

Since my Nvidia Shield upgraded to Plex client 7.30.2.16712 (e2fecda3) It doesn't seem to work properly with Synclounge.  When using it with a custom (my own with the docker image) or a US server - the Shield plays the selected video but video does not distribute to others in the room, nor does the synclounge app show that any video is selected by the room owner.   If I use the web player instead of the shield it works properly.  Please advise.

Thanks,

Rett Walters

**Comment by samcm** [comment]
A potential fix was recently merged & pushed to the docker image. Could you please try again with the updated version?

**Comment by foundationkitty** [comment]
Having a similar issue here on a Nexus Player, also with both the official US servers and my own docker hosted server. I cannot even get the video to play however. Web player and roku work fine.

**Comment by whoiscoos** [comment]
Nvidia Shield no longer works. I am using the regular docker container. SL connects fine but when I hit play, nothing happens for Shield clients.

**Comment by aptalca** [comment]
This is the error in the nvidia shield network logging: https://pastebin.com/iwr5epng

I can send playback to the device maybe 20% of the time. But the current playback status/info is never retrieved by the synclounge webapp.

**Comment by thatcow** [comment]
Still a problem for me as well. Can't get it work with the latest docker image.

Using an older docker image that I had works fine.

**Comment by ttshivers** [comment]
This is an issue on Plex's end and this [forum post](https://forums.plex.tv/t/no-session-status-when-starting-playback-on-shield-over-remote-control-api/555067) appears to be tracking the issue.
