### ISSUE TITLE
Plex Player (macOS Catalina) not showing in Synclounge

### ISSUE THREAD

**Issue by Te-eMster** [samcm/synclounge#182]
Hi, I cannot get my Plex desktop app on macOS Catalina 10.15.4 to show up in the Synclounge app, even though it is listed in the autorized devices list in Plex. My iPad app shows up just fine. However, my friend's desktop app also appears in the Synclounge list when he logs into my Plex account. He is still running on macOS Mojave. Is there a problem with Catalina permissions or is this a Synclounge or Plex issue?

**Comment by gcordalis** [comment]
The current Plex Desktop app doesn't work for some people - we haven't troubleshooted this yet.
A workaround is to use Plex Media Player - https://btsz.nz/pmp
