### ISSUE TITLE
PS4 Plex Player

### ISSUE THREAD

**Issue by xthursdayx** [samcm/synclounge#186]
**Describe the solution you'd like**
I was just wondering if getting synclounge to work via Plex on PS4 is still something that is being worked on?

Also wondering if there are ways to help with that.

**Comment by MagicalCodeMonkey** [comment]
It's up to Plex to configure the console applications to be able to work if they can. It could be a limitation on the device as well.

There is troubleshooting information on Plex's site on how to get debug information from the Plex app. So, you should be able to do that to get information on what is happening on the PS4 side.

The way SyncLounge communicates with the clients is using the following endpoints on the client:
- /player/timeline/poll
- /player/playback/playMedia
- /player/playback/play
- /player/playback/pause
- /player/playback/stop
- /player/playback/seekTo

Prefix these with `http://<client_ip>:<client_port>`
You can get your client's IP and ports by going to `https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=YourPlexTokenGoesHere`

If you can't get things like `http://<client_ip>:<client_port>/player/playback/<play/pause>` to work, then it is likely a limitation of the client. SyncLounge also relies on `/player/timeline/poll` to check synchronization.

If you start looking into this, find me on Discord and we can discuss more indepth.
