### ISSUE TITLE
Unable to select player other than Synclounge player

### ISSUE THREAD

**Issue by sciaio** [samcm/synclounge#188]
If you haven't already, be sure to check the **How-to Report an Issue page** before reporting an issue: https://docs.synclounge.tv/how-tos/report_an_issue/

Please complete the following when reporting a bug/an issue.

### Web App
You can remove this section if your issue isn't related to the Web App

**System Details**

- Operating System: windows 10
- Web Browser name and version: Edge/Chrome v81.0

**Plex Media Server details**

- Version: 1.19.1
- Operating System (Windows/Linux/Mac): Linux (on Qnap NAS)
- Running in Docker? (Yes/No): No
- Location (Local/Remote): Local (LAN)
- Remote Access Enabled (Yes/No)?: Yes

**Plex Client details**

- Name: Plex for Windows
- Version: 1.8.2
- Network connection (Wired/Wifi): Wired
- Platform: Windows 10

### Issue information

When I am in the page http://app.synclounge.tv/#/clientselect I can choose from a list the player where it shows me every player i recently viewed from. However, when I send the invitation on a remote friend it only shows SyncLounge Player (Recommended). They have installed the same Plex for Windows version like mine (right now 1.8.2.1192-89432618 recently updated). We downloaded this from the [official site]( https://www.plex.tv/media-server-downloads/#plex-app). On every computer on my LAN I see the options, even with other accounts. How can I solve this situation?

Thanks

**Comment by gcordalis** [comment]
We get the list of players from plex itself and have no control over what players they provide us. Best bet is for your friend to watch something on the plex app and see if it shows up afterwards.

A note, we've had issues connecting to Plex for Windows, you may want to try Plex Media Player instead: https://btsz.nz/pmp
