### ISSUE TITLE
https is not forced/redirected from http on synclounge.tv subdomains

### ISSUE THREAD

**Issue by hex333ham** [samcm/synclounge#212]
### Issue information

**To Reproduce**

- Go to http://app.synclounge.tv or http://docs.synclounge.tv
- See error (not redirected to https site)

**Describe your bug/issue**

Pretty simple one but alot of subdomains on synclounge.tv don't redirect you to the https version, even though a certificate is present when adding https to urls (including Plex OAuth etc.)

This can be done (relatively) easily with small config changes for popular web servers:

* **Nginx** - https://serverfault.com/a/250488
* **Apache** - https://stackoverflow.com/a/16201658/8991005

**Comment by hex333ham** [comment]
to add more info, I'm using firefox 76.0.1 64-bit

apologies if I messed up the ticket format anywhere

**Comment by hex333ham** [comment]
revised as I've just noticed it's all subdomains, the main domain is fine

**Comment by ttshivers** [comment]
For http://app.synclounge.tv, this is intentional as described in #52

**Comment by hex333ham** [comment]
ah righto, apologies then @ttshivers
