### ISSUE TITLE
Party Pausing?

### ISSUE THREAD

**Issue by MrDevanWright** [samcm/synclounge#37]
I saw it in the chat, but it would be great if there was a toggle to allow/disallow users to pause the stream for everyone.

**Comment by MrDevanWright** [comment]
Possibly adding an additional feature with it, allowing the owner to set a pause limit (ie: 1-3 minutes). Going a step further, adding another option to set a refresh limit (ie: 5-10 minutes) for when then are allowed to pause again.

**Comment by Trahloc** [comment]
I'd be happy just letting the other people pause and only host can unpause.  It's not like I know how full their bladder is so I can pause when they need to excuse themselves. I'm in another country from them which is why we're even using this after all.

**Comment by gcordalis** [comment]
We’ve had a chat about this and it falls quite low on the priority list of things to look at. 

For some context about our reasoning behind not including this already - we’ve found with our group of friends that when someone goes to the bathroom they let us know and the host pauses it. 

We’re always in a call when we use SL so that might give some bias to our take on things.

**Comment by dgw** [comment]
> We’re always in a call when we use SL so that might give some bias to our take on things.

That would be a pretty big source of bias, I think. SL has text room chat, too, though, so it's probably no big deal to just send the room a chat message asking to pause. Would be a useful feature to have this at some point, but low priority is fine.

**Comment by Trahloc** [comment]
>but low priority is fine.

Guess I'll add this to occasional check-ups every few months.  My friends and family had little interest in using it once they realized they couldn't pause it if something came up.

**Comment by brettg0396** [comment]
Yeah, I'd urge the devs to reconsider. Seems like a key feature and I arrived at this issue thread from googling how to do it. Bummer.

**Comment by pistone10** [comment]
+1 as well...had several issues watching Christmas movies with family today because they were not able to pause I missed most of the movies staring at the chat to make sure my nieces/nephews could use the restroom

**Comment by samcm** [comment]
Resolved with https://github.com/samcm/synclounge/commit/b966b1a4e82714c3d460aa8fac42badfc7070b78. Will be rolled out to the public servers within the next 24 hours.
