### ISSUE TITLE
Full Screen Chat Window?

### ISSUE THREAD

**Issue by MrDevanWright** [samcm/synclounge#42]
Is it possible to have an option for an always-on-top chat window in full screen, on the WebApp?

**Comment by samcm** [comment]
Wouldn't the chat just distract away from the content? Unless we changed the way chat worked so that it only showed recent messages, there would be a distraction. Even then, a text-box for sending messages would have to be somewhat accessible.

**Comment by MrDevanWright** [comment]
Eh, whatever you think. I just think it'd be cool even to just have a card pop up and show what was said. Obviously make this optional because some people would hate it with a passion. But just an idea.

**Comment by samcm** [comment]
I actually think it'd be really cool if we managed to integrate it un-intrusively. I'll try and find some time to play around with the concept and see what I can come up with.

**Comment by IBeRamen** [comment]
One suggestion would be to make it kind of like Twitch chat with a pop out feature.

**Comment by avion540** [comment]
Another suggestion would be how [YouTube live does it in full screen on mobile devices](https://user-images.githubusercontent.com/14863961/49041003-e11ddb80-f178-11e8-807a-e9e185b2639e.jpg). If the same idea is applied to a desktop's full screen, you could chat with your friends while enjoying the movie full screen. Of course, making this optional like YouTube live does would be good as well.

**Comment by nydave69** [comment]
Could you run the chat across the bottom like a ticker. with a pause/stop
so when something is said it scrolls in and just stays till the next message.
no popup to distract and a slow scroll in would be easy to read and less distracting.

my 2 cents

**Comment by jladicos** [comment]
Netflix Party has a feature like this. You can chat with your friends while you watch the movie without the browser chrome being visible. It's quite nice.
