### ISSUE TITLE
"Music support" 

### ISSUE THREAD

**Issue by coolmule0** [samcm/synclounge#47]
Running Ubuntu media server and Windows and Rasplex clients. I use the same Plex account and PT with 2 browser tabs for the corresponding client devices. As host (either device) I select some music which begins playing on host device, on second client nothing plays and the message pops up

> Failed to find a compatible copy of <music track name>

If I then select some media on the second device through the PT app it skips its timing to be in sync with the host even if the media selected is not the same.

To reiterate PT cannot automatically select media but manually selecting it works

All devices are on the local network with ethernet.
Media Server: Ubuntu 16.04 with Plex Media Server 1.7.5.4035-313f93718
Windows 7 Client: 7 Ultimate with Plex Media Player 3.9.1.
Raspberry Pi 2B Rasplex 1.8.0 with Plex Home Theater 1.8.0.148-573b6d73

**Comment by samcm** [comment]
Music is currently unsupported sorry. I started adding some support last version but it's not complete yet. Hopefully should be there soon but it requires a large amount of work mainly surrounding playqueues which I mentally haven't figured out how to implement. 

Technically the only issue here is the `/search` command not including Music results. If that was fixed everything would sort of work but it would have to keep re-searching every time the track changes - this would be a really really bad experience.

**Comment by psouza4** [comment]
I just had this issue with a video file my first time trying to use PlexTogether with a friend.  Video started playback immediately for me but they received this error on their side.

**Comment by samcm** [comment]
@psouza4 Most of the time that's because we're hamstrung but Plex's search capabilities and title matching. This should improve in v2 but for the meantime manually playing the content is the solution.

**Comment by Xalaxis** [comment]
@samcm Do you think there could be some text added to the Synclounge introduction telling users that music is not supported yet?

**Comment by samcm** [comment]
@Xalaxis It's in the README here on Github but I should definitely add it elsewhere. Sorry about that.

**Comment by trevorsky** [comment]
I've landed here for the same reason - tried to sync music and failed. I just double checked the readme and it doesn't say anything about music not working. What's the story?

**Comment by Xalaxis** [comment]
Can we rename this issue to "Music support" or something slightly more accurate?

**Comment by samcm** [comment]
Good idea - done.

**Comment by aronwk-aaron** [comment]
Any updates on this?

**Comment by carsoni** [comment]
At the risk of being a pain I would also love to see music support in Sync Lounge. App is great BTW. I've just got a self hosted version running on the family chatserver (Matrix-Synapse and Riot).

Unfortunately I also fell foul of a delayed realization that there is "no music support". However in the current difficult times of social distancing and self isolation collaborative and co-operative apps are top of mind. 

We've been at home for 6 weeks now here in Sydney and I've got a weekly virtual cards game going with some mates. Riot for vision and chat, Playingcards.io for a virtual deck and table and (I thought) the cherry on the cake would be a shared music space.

I'm happy to get involved to see if I can help to get the music side up and running (no promises of course :-) ) .

Let me know if you want to share your "music support" thinking and issues
Regards
Ian

**Comment by qwerzl** [comment]
Any updates on this?

**Comment by habnabit** [comment]
definitely interested in helping to implement this. what is the reason music is separate enough to be unsupported, unlike any other media type? the official plex client(s) don't support this either.

**Comment by BornToDoStuff** [comment]
Is the `/search` command still stupid and doesnt include music so we cant sync music with people? :(
