### ISSUE TITLE
[v2] Rewrite

### ISSUE THREAD

**Issue by samcm** [samcm/synclounge#57]
If I have the time over the Christmas break I'd like to rewrite the core of PT a 3rd time. The front-end UI would largely be the same, but the front-end code would be completely refactored. 

Some goals:
- No callbacks, use async/await with promises. At the moment the codebase is a clown fiesta of callbacks, largely because I learnt JS while writing PT. If we swap to async/await some situations will be much easier to handle, like waiting for PTPlayer to subtly seek-over-time to get back inline with the host. This would also allow for new features to be added much more easily.
- Vuex store broken down in to modules.
- Improve PTPlayer compatibility to allow for direct play. 
- Navigation rewritten so that everything isn't embedded within /sync. Everything that requires the user to be authenticated, connected to a server and in a room should be handled within App.vue. All other routes should be handled within the router-view of App.vue.
- Potentially rewrite the server. At the moment the server codebase isn't too bad, but I'd really like to have 0 callbacks. Currently I'm somewhat afraid of touching the server code as it works (and works well), and swapping to a promise-based codebase would help.

**Comment by Nolsen84** [comment]
Just came across this project, browsing around a bit and I find this.....  **A clown fiesta**!!!!  That's the best thing I've heard all year...

**Comment by samcm** [comment]
DONEZO!
