### ISSUE TITLE
PlexTogether does not pull 'Poster' data in some fields

### ISSUE THREAD

**Issue by La-Mulana** [samcm/synclounge#60]
Like, in Plex you can select your own thumbnail to display for each show by clicking the little pencil and then poster, and the backgrounds for the series page (which I don't personally care too much about)
some of the default images for my shows look a little jank in PTPlayer though so it'd be a nice little feature if they used the ones I selected in plex
obviously not a major concern since it doesn't affect functionality, just sorta nice

Specific fields confirmed affected are the homepage and "On Deck"

issue post requested by samcm

**Comment by samcm** [comment]
I think this is because the On-Deck items take the 'art' field from each library item rather than the 'thumb' - largely because they are different aspect ratios. If you change the Series Background item when editing the series it'll be reflected in SL.
