### ISSUE TITLE
PlexTogether and Playback Settings Sticking Improperly

### ISSUE THREAD

**Issue by La-Mulana** [samcm/synclounge#61]
minor issue, but when watching episodes of [show] it defaults to subs on, but the dropdown indicates subs off, so I have to 'turn subs on' then turn them off again in order to watch without subs

on a related note, I also have a feature request to be able to edit playback settings for an episode before beginning the video playback, which would work around this issue as well

git post requested by samcm

**Comment by samcm** [comment]
I've done a bit of investigating with this and I believe it's to do with the language preferences on the Plex account. If they are correct this is actually functioning as intended despite our initial thoughts. 

You can change them here:
https://app.plex.tv/desktop#!/account/audio-subtitle
