### ISSUE TITLE
Unable to Connect to my Own Server ? 

### ISSUE THREAD

**Issue by Comfubar** [samcm/synclounge#64]
Operating System: Windows 10
        Web Browser Firefox or Chrome
    Plex Media Server details
        Version v1.10.1.4602-f54242b6b
        Operating System Windows 10
        Location (Local/Remote) Local
    Plex Client details
       Version Plex.tv itself
        Network connection (Wired/Wifi) : Wired
        Platform

So I basically just set this up using Docker and have it forwarded to my Domain and all but once in the room to select my Plex Server is states it is unable to connect to my Server I can connect to friends servers but mine I am unable 

https://i.imgur.com/4WT6did.png

**Comment by samcm** [comment]
Is your server behind a reverse-proxy or something?

**Comment by Comfubar** [comment]
Sorry for the late response been working like crazy nope no reverse-proxy nothing like that 
my server is up and running and everything I can connect to it and I can connect to Synclounge
but can't connect to my server through Synclounge at all for some reason 

I can, however, connect to the random ones that have plex account that I've added as friends but I cannot connect to mine could it be a plex setting or something ?

**Comment by samcm** [comment]
Hmm this is a weird one. Some people have had issues with Adblocker denying connections from within the app so maybe try disabling that if you have one installed. 

The developer console within Chrome might give you a better idea of whats going on. Just make sure not to copy-paste anything out of there because there is tokens etc laying around in URLs.

**Comment by Comfubar** [comment]
Ok cool I'll take a look and respond back with what I found

**Comment by Comfubar** [comment]
Seems to have fixed itself but I did find another issue 

So I run mine from docker and all every time I run it 
It tells me its already in use by a container ect im new to docker so i change the --name= to get it to work every single time is there something im doing wrong stupidly with me being new to docker

docker run --name=plextogether -p 8088:8088 -p 8089:8089 -e DOMAIN=mydomain.com starbix/plextogether

**Comment by samcm** [comment]
Glad it's fixed!

You should only have to run the `docker run` command once. From there you can run `docker ps -a` to see your running docker containers and their respective status. You can then start them by running `docker start plextogether`, for example.

**Comment by Comfubar** [comment]
ahh ok thank you @samcm

**Comment by fithwum** [comment]
every time i use the invite link to join a room i get a 404 error and it will not work at all.

the page only says

This content was generated by PHP

And this content is static HTML

**Comment by dgw** [comment]
That sounds like a server misconfiguration @fithwum. PHP should be nowhere near this nodejs app.

**Comment by fithwum** [comment]
i do have apache running my website could that be what the problem is?
also i cant find a folder in appdata for synclounge is it somware else maybe?

**Comment by samcm** [comment]
@fithwum Sounds like the --url flag is incorrectly configured for the webapp. Please post a new issue if you can't fix it.
