### ISSUE TITLE
Support for PlexKodiConnect

### ISSUE THREAD

**Issue by joswart** [samcm/synclounge#65]
I am using Kodi with PlexKodiConnect plugin for most of my playback (TV support in Plex is still very limited).

It would be awesome if synclounge could support PKC as well.

**Comment by samcm** [comment]
I can definitely look in to that, potentially for V2. Does PKC show up here? 

https://plex.tv/api/resources?includeHttps=1

You may have to have it running and then leave it for a few minutes to show up.

**Comment by joswart** [comment]
For some reason I am not authenticated there. I get a "Please sign in" response.

Tried it directly from the same tab where my plex interface was running, but same response. I know that PKC shows up in the IOS app.

**Comment by samcm** [comment]
From looking at PlexKodiConnect it seems that they don't have a HTTP API OR they don't register with plex.tv :(

Unfortunately we need both of these to interact with the client. Closing for now - if this ever changes in the future please tag me.
