### ISSUE TITLE
Hosting My Own Server

### ISSUE THREAD

**Issue by AJDxB** [samcm/synclounge#70]
I'm having difficulties hosting my own server instead of hosting through the preset SyncLounge servers.
I have no idea whether to use the port 8080, 8088, 8089, or something else entirely.

Any instructions or steps on how to achieve hosting my own server on SyncLounge?

**Comment by samcm** [comment]
There is some instructions in the readme but they assume some Nodejs experience. What are you stuck on? The Webapp runs on port 8088, and the Server runs on 8089 by default. 

Have you checked out the docker container? Might be an easier option. https://hub.docker.com/r/starbix/synclounge/

**Comment by AJDxB** [comment]
Hello,

I assumed at first that it was as easy as just port forwarding 8088 and 8089. After that all I would have to do was write https://localhost or something of that sort.
I have no Docker nor Nodejs experience, any idea on what I should do in this case?
I opened the link https://hub.docker.com/r/starbix/synclounge/ but I have absolutely no idea what I'm reading.

Any sort of clear step by step instruction would be helpful. I realize that this is a pain to provide but it might serve as a guide to whoever wishes to host his own server and has no experience with either Docker or Nodejs.

Thank you

**Comment by samcm** [comment]
I believe this was solved in Discord PMs. Closing for now.

**Comment by daicain** [comment]
> I believe this was solved in Discord PMs. Closing for now.

Would be nice if y ou post it so other people could see how its done as well

**Comment by Tmyrene** [comment]
What did you see samcm! WHAT DID YOU SEE!!

**Comment by jsorondo** [comment]
Guys if you don't want to expose the ports to the internet you can use nginx as a reverse proxy and make sure you configure the locations (/slweb[8088] and /slserver[8089]) properly. Then your URL to access the server would be something like https://host.domain.com/slserver
