### ISSUE TITLE
Can't connect to client behind proxy

### ISSUE THREAD

**Issue by annualstatement** [samcm/synclounge#74]
Hi, 
This is my first time hearing about and setting up synclounge. I currently have it running through a docker in open media vault and can access the site via my domain. However when I try to connect to the client, it throws the "error connecting to client." If i use my localhost address, it connects just fine though. Any help would be appreciated, thanks.

**Comment by samcm** [comment]
Are you loading the site via HTTPS?

**Comment by annualstatement** [comment]
I believe so.

**Comment by samcm** [comment]
That'll most likely be why then, have a look at #52 for more info. Sorry!
