### ISSUE TITLE
Sometimes SyncLounge plays the wrong episode

### ISSUE THREAD

**Issue by colonelkrud** [samcm/synclounge#77]
This is a v2 issue. Sometimes SyncLounge tells PMP to play the wrong episode. i will try to grab logs and recreate this issue. This behavior is not consistent. It will play the correct movie files and some series will play normally. Other series will cause it to queue up the wrong episode. Attempting to stop and restart the stream caused strange participant behavior such as skipping ahead or repeatedly restarting the episode.

**Comment by samcm** [comment]
Heya, thanks for the report. Unfortunately this is somewhat of a limitation with how SyncLounge & Plex works. We search all available servers for the `title` of the content the host is playing. Obviously this can lead to some pretty inconsistent results, especially when the title isn't unique like 'Episode 3'.  If you can get me a reproducible setup I could maybe see if this is an edge case that I could take in to account.

V2 massively reduced the chance of this happening by attempting to match both title (by % based threshold) and duration (within 5 seconds either way). If that fails, it will attempt to play the exact content from the same server as the host (if they have access).

A temporary solution for this issue would be to disable Autoplay within `SyncLounge Settings`.  This should allow you to manually play the content.

**Comment by samcm** [comment]
This should be somewhat fixed on the v2 branch now, will roll out over the next few hours. The solution is still not perfect but will hopefully fix a few edge cases.
