### ISSUE TITLE
Link directly to room

### ISSUE THREAD

**Issue by slcc2c** [samcm/synclounge#79]
It would be great to be able to link people directly to a room. My less technical friends have a hell of a time joining.

**Comment by gcordalis** [comment]
This is already a feature.

Once you've hosted a room there is big yellow invite button in the navigation bar at the top. You can share that with your friends to join.

**Comment by slcc2c** [comment]
Idk how I missed that, I did look.

**Comment by gcordalis** [comment]
No probs!
