### ISSUE TITLE
Confusing player-picking-screen

### ISSUE THREAD

**Issue by profile90** [samcm/synclounge#80]
When I was showing this to a multitude of my friends, they were all confused by the first screen - and most did not know what to do or click. This was not intuitive to them:

![](http://plextogether.com/img/screenshots/1-players.png)

**Comment by gcordalis** [comment]
Thanks for raising this.

Once you explained this to them did they understand? Do you have a suggestion for how this could be different to make it easier for them?

**Comment by profile90** [comment]
After a while, they sort of got it. I was also confused at first, though. But, I suppose making the options more obvious, hence larger and add icons for differing types?

**Comment by gcordalis** [comment]
I'll have a think and speak to @samcm about it. I think we can probably make the messaging a bit clearer and use different type to make each option more obvious.

**Comment by profile90** [comment]
I have a few more qualms with the next steps too, I'll post those as well. I'm going to be super annoying :P

**Comment by gcordalis** [comment]
If you can, join us on our [Discord](https://discord.gg/Cp9RPSJ) server and we can have a chat there!

**Comment by samcm** [comment]
I've got some ideas on how to improve this and have somewhat started on the v2 branch. More to come there.

Ps. You should be accessing SL via app.synclounge.tv or v2.synclounge.tv for the latest version :)

**Comment by samcm** [comment]
I further reworked this screen on v2, please check it out when you get a chance :)

v2.synclounge.tv
