### ISSUE TITLE
Playing on the Plex Server Host

### ISSUE THREAD

**Issue by colonelkrud** [samcm/synclounge#81]
My desktop hosts a plex server and allows remote sessions. This sometimes causes a `CORS request did not succeed` error. One solution would be to know when the plex server is on the same host attempting to stream and use localhost instead of the LAN or WAN ip. Possibly defining a custom plex server from inside synclounge? V2 synclounge. plex server Version 1.13.4.5251. Plex media player Version 3.57.1. Desktop environment: macOS High Sierra 10.13.5

**Comment by samcm** [comment]
Hey, thanks for the detailed issue.

Question, are you running your Plex server through a reverse proxy? Plex by default will not run into `CORS` errors, and a misconfigured reverse proxy can sometimes strip the required headers. Unfortunately defining a custom Plex server here wouldn't help as a request to `localhost` will still be blocked by `CORS` - unless you're loading Synclounge from localhost as well.

**Comment by colonelkrud** [comment]
No reverse proxy. It is behind a NAT though and has the port forwarded to it in pure-NAT reflection mode. Synclounge claims to be connecting to the correct local ip but gets a CORS error and times out. Plex itself works fine inside and outside my lan and synclounge works on other players. Just when I’m trying to connect from synclounge to my local desktop. I am using a custom synclounge server.. but that is on another host and has been working fine as well. 

Playing around with my NAT, running a rule to catch any traffic on 32400 in my LAN and redirect it to my desktop local ip seems to fix this issue as well. What is strange is that the ip synclounge is trying to connect to doesn’t change with the NAT rule.

**Comment by samcm** [comment]
Is the URL that is 'correct' a `.plex.direct` one? If so I've seen some issues here and there with DNS-Rebind not working/being blocked which might explain it. Either way I'm not sure there is anything that I could do within the code to try and fix this. I think if you define a server manually you'll still run in to the same issue.

**Comment by colonelkrud** [comment]
In the Plex server advanced configuration, I added an appropriate custom domain. This too gave the Cors error but when I defined the custom domain as “http” instead of “https”, I was able to get around the bug.

**Comment by samcm** [comment]
Gotcha, that's weird! Closing this for now :)
