### ISSUE TITLE
Not working on windows Plex Media Player app or the Webapp

### ISSUE THREAD

**Issue by TheraNinjaCat** [samcm/synclounge#84]
I've tried to get this working on my server, and it all runs and signs in properly, however when I try to play a video nothing happens. This was when it was connected to the desktop application. I then tried with the webapp, and had the same issue, it loads the video, then immediately closes it again. I was about to post this issue but it then occured to me to test it with the iOS mobile app, of which proceeded to work perfectly fine. This leads me to believe there has been a recent update or change to Plex desktop client and/or webapp which might be causing an issue. I'm happy to provide error logs, but I've not found anything so I'd need instructions on how to get that.

**Comment by samcm** [comment]
Heya, Have you had a chance to revisit this? If I could grab your `Plex Media Server` version as well that'd be super handy.

**Comment by Gregor-Best** [comment]
Hey Sam,

The server version is `1.13.5.5291-6fa5e50a8
Linux 4.9.0-5-amd64 (#1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04))`
The "web" version (from https://app.plex.tv) is `3.65.1`
The "web" version (from the desktop client) is `3.63.1`
Synclounge is version 2.0, build #93c3b15
The IOS version is `5.2`
The latest desktop version for windows on their website is `2.16.0.885-f2338b5e` which I'm probably on, I've not found a place to verify that though.
My desktop is Windows 10  Pro, version1803, build 17134.165

I hope this helps, if you need any more information just ask. I've managed to successfully use the web client on synclounge itself, so I got it to at least function, but it'd still be great to use the other devices too.

**Comment by samcm** [comment]
Thanks for the info! To clarify here, were you trying to connect to the Plex.tv webapp in the original issue? 

Either way if everything is working OK in the Synclounge Player then we can probably rule out a PMS issue.  I've managed to connect to PMP today so I'm not sure what's going on there.

**Comment by samcm** [comment]
Yeah I'm running the same versions pretty much across the board. Maybe try running PMP in TV mode or vice versa?

Synclounge won't be able to connect to external clients if the page is loaded over HTTPS.

**Comment by Gregor-Best** [comment]
Ok So I just tried PMP in TV mode and it goes into the splash view, but doesn't actually play the video (which does play when I manually start it independently of synclounge). I completely uninstalled and reinstalled PMP including the appdata folder (it occured to me remaining settings from SVP might have been causing issues), and updated synclounge to the latest version, but it still does the same thing in TV mode, and in not-tv mode, it does the same thing as before, where it just flashes up briefly, but otherwise fails. 
I think it's probably just going to be best to give up, and mark this as unable to reproduce ¯\\_(ツ)\_/¯
I think I'll just use the synclounge webapp...

**Comment by ThatOneLegion** [comment]
I'm having the same issue, here's a recording of what it looks like: https://streamable.com/hi2dj

It does however work in TV Fullscreen mode.

**Comment by briankendall** [comment]
I'm also having the same issue on the macOS version of Plex Media Player. I see exactly the same behavior as shown in the video posted by @ThatOneLegion.

PMS version: 1.13.5.5332
