### ISSUE TITLE
Invite Button missing

### ISSUE THREAD

**Issue by rix1337** [samcm/synclounge#87]
On my custom webroot/serverroot v2 Server the Invite Button has gone missing.

Let me know what further info to provide 😄

**Comment by samcm** [comment]
I think I should be able to reproduce this one, should be a quick fix.

**Comment by samcm** [comment]
Actually I'm not 100% this one will be fixed yet - is there any chance you could have a look in your network tab within Chrome Dev Tools once you join a room? A `HTTP POST` request should be sent off to the webapp. Maybe the `webroot` is causing havoc here but I couldn't reproduce it locally.

**Comment by rix1337** [comment]
Ah, I see whats going on. The post is sent to https://my.domain/invite instead of https://my.domain/webroot/invite

Naturally it yields a 404.

**Comment by rix1337** [comment]
Okay, reporting back. I now see the invite Button, but the clipboard contains:
https://my.domain/invite/invitecode instead of https://my.domain/webroot/invite/invitecode

One last fix? 😛

**Comment by samcm** [comment]
Thanks for the details, will probably get around to fixing that up later today. 👍

**Comment by rix1337** [comment]
Super, that worked. Thank you for your hard work. 2.0 is awesome!

**Comment by samcm** [comment]
Glad to hear it worked! Enjoy.
