### ISSUE TITLE
Official Plex Kodi Addon Support

### ISSUE THREAD

**Issue by Defs3c** [samcm/synclounge#91]
Hi, I can't seem to find the official plex kodi addon in the client selection. Is there any plans to support it?

Thanks.

**Comment by samcm** [comment]
There was a previous issue here #65 for Plex Kodi Connect. Not sure if the official client is any different though. Essentially if the Client doesn't advertise itself to Plex.tv we can't/won't support it.

**Comment by Defs3c** [comment]
Is there a way to check if it advertises itself?

**Comment by mighty2nyce** [comment]
Does anyone know how to get Kodi on Apple TV 4 and get it to stay without having to put it back on every 7 days?! I been searching all day

**Comment by samcm** [comment]
@mighty2nyce please don't post irrelevant issues here..

@Defs3c If it doesn't show up in SyncLounge it probably doesn't advertise itself. You could double check if there is a `allow remote control` setting somewhere as well.
