### ISSUE TITLE
V2 issue with PMP hosting a room

### ISSUE THREAD

**Issue by colonelkrud** [samcm/synclounge#92]
PMP version 3.71.1 seems to have an issue syncing content to the room. A selection can be made from the built in synclounge player and PMP will sync perfectly, but when PMP is hosting the video will have sync issues. I am hosting my own v2 server and we are using the public v2 website. No logs on the server.

**Comment by ultimate255** [comment]
Can confirm, having the same issue.

If the host uses PMP, the other PMP clients fail to sync.

**Comment by samcm** [comment]
I've seen a couple reports of this over the last few weeks but haven't had time to look in to it unfortunately. Use either OpenPHT or the inbuilt player until I can investigate I guess. Unless someone submits a PR I wouldn't expect a super quick turnaround :(

**Comment by ultimate255** [comment]
Seems to be fixed. Was able to host on PMP without any issues.

**Comment by samcm** [comment]
Yup sorry I totally forgot to update this issue. I believe I fixed this late December - thanks for confirming!
